//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.RecursoIdioma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rec {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rec() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaPresentacion.RecursoIdioma.Rec", typeof(Rec).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accion.
        /// </summary>
        internal static string Accion {
            get {
                return ResourceManager.GetString("Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activos.
        /// </summary>
        internal static string Activos {
            get {
                return ResourceManager.GetString("Activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Clasificacion realizada con Exito..
        /// </summary>
        internal static string AltaClasiExito {
            get {
                return ResourceManager.GetString("AltaClasiExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Clasificacion no se ha realizado con Exito..
        /// </summary>
        internal static string AltaClasiSinExito {
            get {
                return ResourceManager.GetString("AltaClasiSinExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        internal static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitacora.
        /// </summary>
        internal static string Bitacora {
            get {
                return ResourceManager.GetString("Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string BtnAgregar {
            get {
                return ResourceManager.GetString("BtnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Idioma.
        /// </summary>
        internal static string BtnCambiarIdioma {
            get {
                return ResourceManager.GetString("BtnCambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string BtnCliente {
            get {
                return ResourceManager.GetString("BtnCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string BtnConsultar {
            get {
                return ResourceManager.GetString("BtnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos.
        /// </summary>
        internal static string BtnDescuento {
            get {
                return ResourceManager.GetString("BtnDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión.
        /// </summary>
        internal static string BtnGestion {
            get {
                return ResourceManager.GetString("BtnGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string BtnProducto {
            get {
                return ResourceManager.GetString("BtnProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string BtnUsuario {
            get {
                return ResourceManager.GetString("BtnUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vender.
        /// </summary>
        internal static string BtnVender {
            get {
                return ResourceManager.GetString("BtnVender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        internal static string BtnVentas {
            get {
                return ResourceManager.GetString("BtnVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string CapBackup {
            get {
                return ResourceManager.GetString("CapBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string CapCerrar {
            get {
                return ResourceManager.GetString("CapCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesion..
        /// </summary>
        internal static string CapCerrarSesion {
            get {
                return ResourceManager.GetString("CapCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmacion.
        /// </summary>
        internal static string CapConfirmacion {
            get {
                return ResourceManager.GetString("CapConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CapError {
            get {
                return ResourceManager.GetString("CapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restauracion.
        /// </summary>
        internal static string CapRestore {
            get {
                return ResourceManager.GetString("CapRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesion.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificacion.
        /// </summary>
        internal static string Clasificacion {
            get {
                return ResourceManager.GetString("Clasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Clasificacion.
        /// </summary>
        internal static string CodigoClasificacion {
            get {
                return ResourceManager.GetString("CodigoClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo  Cliente.
        /// </summary>
        internal static string CodigoCliente {
            get {
                return ResourceManager.GetString("CodigoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro Producto.
        /// </summary>
        internal static string CodigoProdutco {
            get {
                return ResourceManager.GetString("CodigoProdutco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Tipo de Producto.
        /// </summary>
        internal static string CodigoTipoProducto {
            get {
                return ResourceManager.GetString("CodigoTipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Unidad Medida.
        /// </summary>
        internal static string CodigoUm {
            get {
                return ResourceManager.GetString("CodigoUm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Usuario.
        /// </summary>
        internal static string CodigoUsuario {
            get {
                return ResourceManager.GetString("CodigoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Unidad de Medida.
        /// </summary>
        internal static string CodUnidadMedida {
            get {
                return ResourceManager.GetString("CodUnidadMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras Presenciales.
        /// </summary>
        internal static string ComprasPresenciales {
            get {
                return ResourceManager.GetString("ComprasPresenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concretar Venta.
        /// </summary>
        internal static string ConcretarVenta {
            get {
                return ResourceManager.GetString("ConcretarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmarVenta.
        /// </summary>
        internal static string ConfirmarVenta {
            get {
                return ResourceManager.GetString("ConfirmarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        internal static string Descuento {
            get {
                return ResourceManager.GetString("Descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento de la Semana.
        /// </summary>
        internal static string DescuentodelaSemana {
            get {
                return ResourceManager.GetString("DescuentodelaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string Detalle {
            get {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Factura N°:.
        /// </summary>
        internal static string DetalleFacturaN {
            get {
                return ResourceManager.GetString("DetalleFacturaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Factura N°:.
        /// </summary>
        internal static string DetNroFac {
            get {
                return ResourceManager.GetString("DetNroFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        internal static string Domingo {
            get {
                return ResourceManager.GetString("Domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTO %.
        /// </summary>
        internal static string DTO_ {
            get {
                return ResourceManager.GetString("DTO%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminados.
        /// </summary>
        internal static string Eliminados {
            get {
                return ResourceManager.GetString("Eliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Adhesion.
        /// </summary>
        internal static string FechaAdhesion {
            get {
                return ResourceManager.GetString("FechaAdhesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        internal static string FechaNacimineto {
            get {
                return ResourceManager.GetString("FechaNacimineto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Pedido.
        /// </summary>
        internal static string FormaDePedido {
            get {
                return ResourceManager.GetString("FormaDePedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        internal static string Importe {
            get {
                return ResourceManager.GetString("Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesion.
        /// </summary>
        internal static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jueves.
        /// </summary>
        internal static string Jueves {
            get {
                return ResourceManager.GetString("Jueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes.
        /// </summary>
        internal static string Lunes {
            get {
                return ResourceManager.GetString("Lunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martes.
        /// </summary>
        internal static string Martes {
            get {
                return ResourceManager.GetString("Martes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar al menos un producto para Agregar a la venta..
        /// </summary>
        internal static string MessageAgregaralemnosun {
            get {
                return ResourceManager.GetString("MessageAgregaralemnosun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Alias ingresado ya se encuentra registrado por otro Usuario..
        /// </summary>
        internal static string MessageAliasIngresadoyaregistrado {
            get {
                return ResourceManager.GetString("MessageAliasIngresadoyaregistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Tipo de Producto realizada con Exito..
        /// </summary>
        internal static string MessageAltaTipoProdExito {
            get {
                return ResourceManager.GetString("MessageAltaTipoProdExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Tipo de Producto no se ha realizado con Exito..
        /// </summary>
        internal static string MessageAltaTipoProDNOExtio {
            get {
                return ResourceManager.GetString("MessageAltaTipoProDNOExtio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Unidad de Medida realizada con Exito..
        /// </summary>
        internal static string MessageAltaUMExito {
            get {
                return ResourceManager.GetString("MessageAltaUMExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Unidad de Medida no se ha realizado con Exito..
        /// </summary>
        internal static string MessageAltaUMNOExtio {
            get {
                return ResourceManager.GetString("MessageAltaUMNOExtio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Realizado con Exito..
        /// </summary>
        internal static string MessageBackupExito {
            get {
                return ResourceManager.GetString("MessageBackupExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI ingresado ya se encuentra registrado..
        /// </summary>
        internal static string MessageboxDniyaregistrado {
            get {
                return ResourceManager.GetString("MessageboxDniyaregistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe haber almenos un producto por adquirir..
        /// </summary>
        internal static string MessageCargaralmenosunprod {
            get {
                return ResourceManager.GetString("MessageCargaralmenosunprod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar un codigo para filtrar..
        /// </summary>
        internal static string MessageCargarCodigoParafiltrar {
            get {
                return ResourceManager.GetString("MessageCargarCodigoParafiltrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar la contraseña para continuar..
        /// </summary>
        internal static string MessageCargarContraseña {
            get {
                return ResourceManager.GetString("MessageCargarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar el usuario para continuar..
        /// </summary>
        internal static string MessageCargarUsuario {
            get {
                return ResourceManager.GetString("MessageCargarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Bitacora..
        /// </summary>
        internal static string MessageCerrarBitacora {
            get {
                return ResourceManager.GetString("MessageCerrarBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar el programa..
        /// </summary>
        internal static string MessageCerrarPrograma {
            get {
                return ResourceManager.GetString("MessageCerrarPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente se ha dado de alta con Exito..
        /// </summary>
        internal static string MessageClienteDadoAlta {
            get {
                return ResourceManager.GetString("MessageClienteDadoAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente modificado con Exito..
        /// </summary>
        internal static string MessageClienteModificado {
            get {
                return ResourceManager.GetString("MessageClienteModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea confirmar la Venta?.
        /// </summary>
        internal static string MessageConfirmarVenta {
            get {
                return ResourceManager.GetString("MessageConfirmarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Cargar la Clasifiacion.
        /// </summary>
        internal static string MessageDebecargarClasi {
            get {
                return ResourceManager.GetString("MessageDebecargarClasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Cargar la Clasifiacion.
        /// </summary>
        internal static string MessageDebeCargarClasificacion {
            get {
                return ResourceManager.GetString("MessageDebeCargarClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar un DNI para realizar la busqueda..
        /// </summary>
        internal static string MessageDebeCargarDNIparabuscar {
            get {
                return ResourceManager.GetString("MessageDebeCargarDNIparabuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar un Nombre para realizar la busqueda..
        /// </summary>
        internal static string MessageDebeCargarNombreparabuscar {
            get {
                return ResourceManager.GetString("MessageDebeCargarNombreparabuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Cargar el Tipo de Producto.
        /// </summary>
        internal static string MessageDebeCargarTipoProducto {
            get {
                return ResourceManager.GetString("MessageDebeCargarTipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar un cliente.
        /// </summary>
        internal static string MessageDebeCargaruncliente {
            get {
                return ResourceManager.GetString("MessageDebeCargaruncliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado con Exito..
        /// </summary>
        internal static string MessageDescuentoActualizado {
            get {
                return ResourceManager.GetString("MessageDescuentoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea cerrar Sesion?.
        /// </summary>
        internal static string MessageDeseaCerrarSesion {
            get {
                return ResourceManager.GetString("MessageDeseaCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI no pertenece a un Socio..
        /// </summary>
        internal static string MessageDNInopertenece {
            get {
                return ResourceManager.GetString("MessageDNInopertenece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI no pertenece a un Socio Activo..
        /// </summary>
        internal static string MessageDniNoperteneceSocioActivo {
            get {
                return ResourceManager.GetString("MessageDniNoperteneceSocioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto ya está en la orden..
        /// </summary>
        internal static string MessageElprodYaesta {
            get {
                return ResourceManager.GetString("MessageElprodYaesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email enviado con Exito..
        /// </summary>
        internal static string MessageEmailEnviado {
            get {
                return ResourceManager.GetString("MessageEmailEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Email no se pudo enviar..
        /// </summary>
        internal static string MessageEmailNoEnviado {
            get {
                return ResourceManager.GetString("MessageEmailNoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al iniciar Sesion, verifique Usuario o Contraseña..
        /// </summary>
        internal static string MessageErroraliniciarSesion {
            get {
                return ResourceManager.GetString("MessageErroraliniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para filtrar por codigo de usuario debe cargar un número..
        /// </summary>
        internal static string MessageFiltrarporcodigodebecargarnumero {
            get {
                return ResourceManager.GetString("MessageFiltrarporcodigodebecargarnumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intentos restantes..
        /// </summary>
        internal static string MessageIntentos {
            get {
                return ResourceManager.GetString("MessageIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Tipo de Producto realizada con Exito..
        /// </summary>
        internal static string MessageModificacionTipoProdExtio {
            get {
                return ResourceManager.GetString("MessageModificacionTipoProdExtio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Tipo de Producto no se ha realizado con Exito..
        /// </summary>
        internal static string MessageModTIpoProdNoExITO {
            get {
                return ResourceManager.GetString("MessageModTIpoProdNoExITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Unidad de Medida realizada con Exito..
        /// </summary>
        internal static string MessageModUMEXito {
            get {
                return ResourceManager.GetString("MessageModUMEXito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Unidad de Medida no se ha realizado con Exito..
        /// </summary>
        internal static string MessageModUMNoExito {
            get {
                return ResourceManager.GetString("MessageModUMNoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay suficiente Stock de este producto para cubrir la venta..
        /// </summary>
        internal static string MessageNohaySuficienteStock {
            get {
                return ResourceManager.GetString("MessageNohaySuficienteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido agregar el usuario, Intentelo de nuevo más tarde.
        /// </summary>
        internal static string messageNosepudoagregarusuario {
            get {
                return ResourceManager.GetString("messageNosepudoagregarusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para filtrar por codigo de Producto debe cargar un numero..
        /// </summary>
        internal static string MessageParafiltrarporCodProd {
            get {
                return ResourceManager.GetString("MessageParafiltrarporCodProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para filtrar por Dni debe cargar un numero..
        /// </summary>
        internal static string MessageParafiltrarpordni {
            get {
                return ResourceManager.GetString("MessageParafiltrarpordni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto dado de alta con Exito..
        /// </summary>
        internal static string MessageProdAlta {
            get {
                return ResourceManager.GetString("MessageProdAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto Modificado con Exito..
        /// </summary>
        internal static string MessageProdModificado {
            get {
                return ResourceManager.GetString("MessageProdModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes acutalizadas con Exito.
        /// </summary>
        internal static string MessageRedesActualizadas {
            get {
                return ResourceManager.GetString("MessageRedesActualizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las redes no se pudieron actualizar..
        /// </summary>
        internal static string MessageRedesNoActualizadas {
            get {
                return ResourceManager.GetString("MessageRedesNoActualizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restauracion realizada con exito..
        /// </summary>
        internal static string MessageRestauracionExito {
            get {
                return ResourceManager.GetString("MessageRestauracionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Socio se ha dado de Alta con Exito..
        /// </summary>
        internal static string MessageSocioDadoAlta {
            get {
                return ResourceManager.GetString("MessageSocioDadoAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le quedan.
        /// </summary>
        internal static string MessageTiene {
            get {
                return ResourceManager.GetString("MessageTiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Agregado Correctamente.
        /// </summary>
        internal static string MessageUsuarioAgregadoCorrectamente {
            get {
                return ResourceManager.GetString("MessageUsuarioAgregadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se ha bloqueado temporalmente, por favor contacta con el gerente..
        /// </summary>
        internal static string MessageUsuarioBloqueado {
            get {
                return ResourceManager.GetString("MessageUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Modificado con Exito..
        /// </summary>
        internal static string MessageUsuarioModificado {
            get {
                return ResourceManager.GetString("MessageUsuarioModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un usuario no puede darse de baja por si mismo del sistema..
        /// </summary>
        internal static string MessageUsuarioNopuededarsedebaja {
            get {
                return ResourceManager.GetString("MessageUsuarioNopuededarsedebaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el Alias del usuario..
        /// </summary>
        internal static string MessageValidacionAlias {
            get {
                return ResourceManager.GetString("MessageValidacionAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el apellido del usuario..
        /// </summary>
        internal static string MessageValidacionApellido {
            get {
                return ResourceManager.GetString("MessageValidacionApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe agregar el apellido del cliente..
        /// </summary>
        internal static string MessageValidacionApellidoCli {
            get {
                return ResourceManager.GetString("MessageValidacionApellidoCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar la clasificacion del producto..
        /// </summary>
        internal static string MessageValidacionClasificacion {
            get {
                return ResourceManager.GetString("MessageValidacionClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un cliente..
        /// </summary>
        internal static string MessageValidacionCliente {
            get {
                return ResourceManager.GetString("MessageValidacionCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la contraseña del usuario..
        /// </summary>
        internal static string MessageValidacionContraseña {
            get {
                return ResourceManager.GetString("MessageValidacionContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la direccion del usuario..
        /// </summary>
        internal static string MessageValidacionDireccion {
            get {
                return ResourceManager.GetString("MessageValidacionDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe agregar la direccion del cliente..
        /// </summary>
        internal static string MessageValidacionDireccionCli {
            get {
                return ResourceManager.GetString("MessageValidacionDireccionCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe cargar el dni del cliente..
        /// </summary>
        internal static string MessageValidacionDNIcli {
            get {
                return ResourceManager.GetString("MessageValidacionDNIcli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un numero en el DNI..
        /// </summary>
        internal static string MessageValidacionDNInumero {
            get {
                return ResourceManager.GetString("MessageValidacionDNInumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un numero de DNI..
        /// </summary>
        internal static string MessageValidacionDNINumeroCli {
            get {
                return ResourceManager.GetString("MessageValidacionDNINumeroCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el DNI correctamente del usuario..
        /// </summary>
        internal static string MessageValidacionDNIvacio {
            get {
                return ResourceManager.GetString("MessageValidacionDNIvacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe cargar el email del cliente..
        /// </summary>
        internal static string MessageValidacionEmailCli {
            get {
                return ResourceManager.GetString("MessageValidacionEmailCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la fecha de nacimiento del usuario..
        /// </summary>
        internal static string MessageValidacionfecha {
            get {
                return ResourceManager.GetString("MessageValidacionfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el nombre del usuario..
        /// </summary>
        internal static string MessageValidacionNombre {
            get {
                return ResourceManager.GetString("MessageValidacionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe agregar el nombre del cliente..
        /// </summary>
        internal static string MessageValidacionNombreCli {
            get {
                return ResourceManager.GetString("MessageValidacionNombreCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar el Nombre del producto..
        /// </summary>
        internal static string MessageValidacionNombreProd {
            get {
                return ResourceManager.GetString("MessageValidacionNombreProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar el precio del producto..
        /// </summary>
        internal static string MessageValidacionPrecioProd {
            get {
                return ResourceManager.GetString("MessageValidacionPrecioProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el rol del usuario..
        /// </summary>
        internal static string MessageValidacionRoles {
            get {
                return ResourceManager.GetString("MessageValidacionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe agregar el Telefono del cliente..
        /// </summary>
        internal static string MessageValidacionTelefonoCli {
            get {
                return ResourceManager.GetString("MessageValidacionTelefonoCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un numero de Telefono..
        /// </summary>
        internal static string MessageValidacionTelefonoCliNumero {
            get {
                return ResourceManager.GetString("MessageValidacionTelefonoCliNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un numero en Telefono..
        /// </summary>
        internal static string MessageValidacionTelefonoNumero {
            get {
                return ResourceManager.GetString("MessageValidacionTelefonoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el telefono correctamente del usuario..
        /// </summary>
        internal static string MessageValidacionTelefonovacio {
            get {
                return ResourceManager.GetString("MessageValidacionTelefonovacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe elegir el tipo de cliente..
        /// </summary>
        internal static string MessageValidacionTipoCli {
            get {
                return ResourceManager.GetString("MessageValidacionTipoCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un tipo de cliente..
        /// </summary>
        internal static string MessageValidacionTipoCliente {
            get {
                return ResourceManager.GetString("MessageValidacionTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un tipo de compra..
        /// </summary>
        internal static string MessageValidacionTipoCOmpra {
            get {
                return ResourceManager.GetString("MessageValidacionTipoCOmpra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un tipo de entrega..
        /// </summary>
        internal static string MessageValidacionTipoENTREGA {
            get {
                return ResourceManager.GetString("MessageValidacionTipoENTREGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar el tipo de producto..
        /// </summary>
        internal static string MessageValidacionTipoProd {
            get {
                return ResourceManager.GetString("MessageValidacionTipoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar la unidad de medida del producto..
        /// </summary>
        internal static string MessageValidacionUnidadMed {
            get {
                return ResourceManager.GetString("MessageValidacionUnidadMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta realizada con Exito.
        /// </summary>
        internal static string MessageVentaConExito {
            get {
                return ResourceManager.GetString("MessageVentaConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miercoles.
        /// </summary>
        internal static string Miercoles {
            get {
                return ResourceManager.GetString("Miercoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Clasificacion realizada con Exito..
        /// </summary>
        internal static string ModClasiConExtio {
            get {
                return ResourceManager.GetString("ModClasiConExtio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificacion de Clasificacion no se ha realizado con Exito..
        /// </summary>
        internal static string ModClasiSinExti {
            get {
                return ResourceManager.GetString("ModClasiSinExti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Activo.
        /// </summary>
        internal static string noactivo {
            get {
                return ResourceManager.GetString("noactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Cliente.
        /// </summary>
        internal static string NombreCliente {
            get {
                return ResourceManager.GetString("NombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        internal static string NombreCompleto {
            get {
                return ResourceManager.GetString("NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Socios.
        /// </summary>
        internal static string NoSocios {
            get {
                return ResourceManager.GetString("NoSocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro Factura.
        /// </summary>
        internal static string NroFactura {
            get {
                return ResourceManager.GetString("NroFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro Producto.
        /// </summary>
        internal static string NroProd {
            get {
                return ResourceManager.GetString("NroProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtencion del Beneficio.
        /// </summary>
        internal static string ObtenciondelBeneficio {
            get {
                return ResourceManager.GetString("ObtenciondelBeneficio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaudo Diario.
        /// </summary>
        internal static string RecaudoDiario {
            get {
                return ResourceManager.GetString("RecaudoDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes.
        /// </summary>
        internal static string Redes {
            get {
                return ResourceManager.GetString("Redes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respaldo.
        /// </summary>
        internal static string Respaldo {
            get {
                return ResourceManager.GetString("Respaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer.
        /// </summary>
        internal static string Restablecer {
            get {
                return ResourceManager.GetString("Restablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restauracion.
        /// </summary>
        internal static string Restauracion {
            get {
                return ResourceManager.GetString("Restauracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de Guardado.
        /// </summary>
        internal static string RutadeGuardado {
            get {
                return ResourceManager.GetString("RutadeGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de Restauracion.
        /// </summary>
        internal static string RutadeRestauracion {
            get {
                return ResourceManager.GetString("RutadeRestauracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabado.
        /// </summary>
        internal static string Sabado {
            get {
                return ResourceManager.GetString("Sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socio.
        /// </summary>
        internal static string Socio {
            get {
                return ResourceManager.GetString("Socio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socios.
        /// </summary>
        internal static string Socios {
            get {
                return ResourceManager.GetString("Socios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cliente.
        /// </summary>
        internal static string TipodeCliente {
            get {
                return ResourceManager.GetString("TipodeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Compra.
        /// </summary>
        internal static string TipodeCompra {
            get {
                return ResourceManager.GetString("TipodeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Entrega.
        /// </summary>
        internal static string TipodeEntrega {
            get {
                return ResourceManager.GetString("TipodeEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Producto.
        /// </summary>
        internal static string TipoProducto {
            get {
                return ResourceManager.GetString("TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Medida.
        /// </summary>
        internal static string UnidadMedida {
            get {
                return ResourceManager.GetString("UnidadMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas del Dia.
        /// </summary>
        internal static string VentaDiaria {
            get {
                return ResourceManager.GetString("VentaDiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        internal static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas del Mes.
        /// </summary>
        internal static string VentasMes {
            get {
                return ResourceManager.GetString("VentasMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        internal static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viernes.
        /// </summary>
        internal static string Viernes {
            get {
                return ResourceManager.GetString("Viernes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
